#!/bin/bash

# Exit on errors
set -eu

# App constantes
MANGAFOX_URL="http://mangafox.me"
APP_VERSION="0.9.2"
APP_PATH=`pwd`

# Chapiter's information
MANGA_TITLE=""
MANGA_VOLUME_NUMBER=""
MANGA_CHAPTER_NUMBER=""
MANGA_CHAPTER_SCANS=""
MANGA_CHAPTER_URL=""
MANGA_CHAPTER_PATH=""

# Application's scripts
source "${APP_PATH}/src/back.sh"
source "${APP_PATH}/src/front.sh"

# Runtime
displayHeader
checkApplicationPath
displayUsageIfRequestedOrIfNoArguments "$@"
checkPastedUrl "$@"                           # step. 1
if ((`userWantsAnEntiereVolume` == 1)); then
  setChapterData                              # step. 2
  checkIfMangafoxIsUp                         # step. 3
  checkIfTheChapterExist "$@"                 # step. 4
  getChapterTotalScansNumber
  setupFoldersToStoreData
  buildChapterFile                            # step. 5
  displayBuiltChapterPath
else
  setMangaData                                # step. 2
  checkIfMangafoxIsUp                         # step. 3
  checkIfTheVolumeExist "$@"                  # step. 4
  getTotalNumberOfChapiters
  setupFoldersToStoreData
  buildVolumeChapiters                        # step. 5
  displayBuiltVolumePath
fi
displayFooter

# Exit with success
exit 0
